server {
  listen 80;
  server_name teleset.local;

  access_log /var/log/nginx/teleset.access.log;
  error_log /var/log/nginx/teleset.error.log;

  gzip on;
  gzip_disable "msie6";
  gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

  client_max_body_size 50m;

  root /var/www/teleset.plus/current/public;

  location / {
    try_files $uri $uri/index.html /index.html;
  }

  location /site {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://web.local/site;
  }

  location /api {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://web.local/site;
  }


  # PRODUCTION: need copy to lbackend
  location /uploads/ {
    root /var/www/teleset.plus/current;
  }

#   location ~* \.(m3u8|ts)$ {
#     add_header 'Access-Control-Allow-Origin' '*';
#     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
#     add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
#     add_header 'Access-Control-Max-Age' 1728000;
#     add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
#   }

  location /informers/ {
    root /var/www/teleset.plus/current;
    try_files $uri $uri.html $uri/index.html;
  }

  location /block {
    root /var/www/teleset.plus/current;
    access_log /var/log/nginx/teleset.plus.block.log;
    try_files $uri $uri.html $uri/index.html $uri/iisstart.htm;
  }

#   location @teleset_unicorn {
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto $scheme;
#     proxy_set_header Host $http_host;
#     proxy_redirect off;
#     proxy_pass http://web.local;
#   }

#  location ~* ".*?\.(ico|css|js|gif|jpg|jpeg|png|doc|pdf|woff2|svg)(\?[0-9]*)?$" {
  location ~ ^/frontend/(img|fonts)/ {
    expires 24h;
    #expires max;
    proxy_cache_valid  200 302  60m;
    proxy_cache_valid  404      1m;
    break;
  }
  error_page 500 502 503 504 /50x.html;

}
